# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import rpc_package.common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='hello.proto',
  package='rpc_package',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0bhello.proto\x12\x0brpc_package\x1a\x0c\x63ommon.proto\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"C\n\nHelloReply\x12$\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x16.rpc_package.ErrorCode\x12\x0f\n\x07message\x18\x02 \x01(\t\"*\n\x0c\x42ytesRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\x32\x99\x01\n\x11HelloWorldService\x12@\n\x08SayHello\x12\x19.rpc_package.HelloRequest\x1a\x17.rpc_package.HelloReply\"\x00\x12\x42\n\x08Transfer\x12\x19.rpc_package.BytesRequest\x1a\x17.rpc_package.HelloReply\"\x00(\x01\x62\x06proto3')
  ,
  dependencies=[common__pb2.DESCRIPTOR,])




_HELLOREQUEST = _descriptor.Descriptor(
  name='HelloRequest',
  full_name='rpc_package.HelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='rpc_package.HelloRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=70,
)


_HELLOREPLY = _descriptor.Descriptor(
  name='HelloReply',
  full_name='rpc_package.HelloReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='rpc_package.HelloReply.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='rpc_package.HelloReply.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=139,
)


_BYTESREQUEST = _descriptor.Descriptor(
  name='BytesRequest',
  full_name='rpc_package.BytesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='rpc_package.BytesRequest.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='rpc_package.BytesRequest.value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=183,
)

_HELLOREPLY.fields_by_name['code'].enum_type = common__pb2._ERRORCODE
DESCRIPTOR.message_types_by_name['HelloRequest'] = _HELLOREQUEST
DESCRIPTOR.message_types_by_name['HelloReply'] = _HELLOREPLY
DESCRIPTOR.message_types_by_name['BytesRequest'] = _BYTESREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'hello_pb2'
  # @@protoc_insertion_point(class_scope:rpc_package.HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREPLY,
  '__module__' : 'hello_pb2'
  # @@protoc_insertion_point(class_scope:rpc_package.HelloReply)
  })
_sym_db.RegisterMessage(HelloReply)

BytesRequest = _reflection.GeneratedProtocolMessageType('BytesRequest', (_message.Message,), {
  'DESCRIPTOR' : _BYTESREQUEST,
  '__module__' : 'hello_pb2'
  # @@protoc_insertion_point(class_scope:rpc_package.BytesRequest)
  })
_sym_db.RegisterMessage(BytesRequest)



_HELLOWORLDSERVICE = _descriptor.ServiceDescriptor(
  name='HelloWorldService',
  full_name='rpc_package.HelloWorldService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=186,
  serialized_end=339,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='rpc_package.HelloWorldService.SayHello',
    index=0,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLOREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Transfer',
    full_name='rpc_package.HelloWorldService.Transfer',
    index=1,
    containing_service=None,
    input_type=_BYTESREQUEST,
    output_type=_HELLOREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_HELLOWORLDSERVICE)

DESCRIPTOR.services_by_name['HelloWorldService'] = _HELLOWORLDSERVICE

# @@protoc_insertion_point(module_scope)
